on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**

name: Deploy Infrastructure to Azure

permissions:
  contents: read
  id-token: write

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      
