on:
  push:
    branches:
      - main
    # paths:
    #   - infrastructure/**

name: Deploy Infrastructure to Azure

permissions:
  contents: read
  id-token: write

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Validate Bicep template
        uses: azure/bicep-deploy@v2
        with:
          type: 'deployment'
          operation: 'validate'
          scope: 'resourceGroup'
          template-file: './infrastructure/main.bicep'
          parameters-file: './infrastructure/prod.bicepparam'
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Deploy infrastructure using Bicep
      #   uses: azure/bicep-deploy@v2
      #   with:
      #     type: 'deployment'
      #     operation: 'create'
      #     scope: 'resourceGroup'
      #     template-file: './infrastructure/main.bicep'
      #     parameters-file: './infrastructure/prod.bicepparam'
      #     resource-group-name: ${{vars.RESOURCE_GROUP_NAME}}
